# fly.toml app configuration file generated for fake-out-game
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

# The name of your Fly.io app. This must be unique across all Fly.io apps.
# If you are getting errors related to app name, try changing this to something unique.
app = 'fakeout'
# The primary region for your app. Choose a region closest to your users for best performance.
# See https://fly.io/docs/reference/regions/ for available regions.
primary_region = 'yyz'

[build]
  # Use the Dockerfile in the root of the repository.
  # If you have a custom Dockerfile path, specify it here, e.g., dockerfile = "path/to/Dockerfile"
  build_args = { NODE_OPTIONS = "--max-old-space-size=4096" }

[env]
  NODE_ENV = 'production'
  PORT = '3001'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    grace_period = '10s'
    interval = '30s'
    method = 'GET'
    timeout = '5s'
    path = '/'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

# Billing limits to prevent overspending
[processes]
  [processes.app]
    hard_limit = 10
    soft_limit = 5
